/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author 182120042
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmGerenciamento = new javax.swing.JMenu();
        jmCliente = new javax.swing.JMenu();
        jmiCCadastrar = new javax.swing.JMenuItem();
        jmiCEditar = new javax.swing.JMenuItem();
        jmiCListar = new javax.swing.JMenuItem();
        jmiCDeletar = new javax.swing.JMenuItem();
        jmEditora = new javax.swing.JMenu();
        jmiECadastrar = new javax.swing.JMenuItem();
        jmiEEditar = new javax.swing.JMenuItem();
        jmiEListar = new javax.swing.JMenuItem();
        jmiEDeletar = new javax.swing.JMenuItem();
        jmLivro = new javax.swing.JMenu();
        jmiLCadastrar = new javax.swing.JMenuItem();
        jmiLEditar = new javax.swing.JMenuItem();
        jmiLListar = new javax.swing.JMenuItem();
        jmiLDeletar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jmGerenciamento.setMnemonic('g');
        jmGerenciamento.setText("Gerenciamento");

        jmCliente.setMnemonic('c');
        jmCliente.setText("Cliente");
        jmCliente.setToolTipText("Cadastrar,Editar,Listar,Deletar Cliente");

        jmiCCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCCadastrar.setMnemonic('c');
        jmiCCadastrar.setText("Cadastrar");
        jmiCCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCCadastrarActionPerformed(evt);
            }
        });
        jmCliente.add(jmiCCadastrar);

        jmiCEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCEditar.setMnemonic('e');
        jmiCEditar.setText("Editar");
        jmiCEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCEditarActionPerformed(evt);
            }
        });
        jmCliente.add(jmiCEditar);

        jmiCListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCListar.setMnemonic('l');
        jmiCListar.setText("Listar");
        jmiCListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCListarActionPerformed(evt);
            }
        });
        jmCliente.add(jmiCListar);

        jmiCDeletar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCDeletar.setMnemonic('d');
        jmiCDeletar.setText("Deletar");
        jmiCDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCDeletarActionPerformed(evt);
            }
        });
        jmCliente.add(jmiCDeletar);

        jmGerenciamento.add(jmCliente);

        jmEditora.setMnemonic('e');
        jmEditora.setText("Editora");

        jmiECadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiECadastrar.setMnemonic('c');
        jmiECadastrar.setText("Cadastrar");
        jmiECadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiECadastrarActionPerformed(evt);
            }
        });
        jmEditora.add(jmiECadastrar);

        jmiEEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiEEditar.setMnemonic('e');
        jmiEEditar.setText("Editar");
        jmiEEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEEditarActionPerformed(evt);
            }
        });
        jmEditora.add(jmiEEditar);

        jmiEListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiEListar.setMnemonic('l');
        jmiEListar.setText("Listar");
        jmiEListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEListarActionPerformed(evt);
            }
        });
        jmEditora.add(jmiEListar);

        jmiEDeletar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiEDeletar.setMnemonic('d');
        jmiEDeletar.setText("Deletar");
        jmiEDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEDeletarActionPerformed(evt);
            }
        });
        jmEditora.add(jmiEDeletar);

        jmGerenciamento.add(jmEditora);

        jmLivro.setMnemonic('l');
        jmLivro.setText("Livro");

        jmiLCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiLCadastrar.setMnemonic('c');
        jmiLCadastrar.setText("Cadastrar");
        jmiLCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLCadastrarActionPerformed(evt);
            }
        });
        jmLivro.add(jmiLCadastrar);

        jmiLEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiLEditar.setMnemonic('e');
        jmiLEditar.setText("Editar");
        jmLivro.add(jmiLEditar);

        jmiLListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiLListar.setMnemonic('l');
        jmiLListar.setText("Listar");
        jmLivro.add(jmiLListar);

        jmiLDeletar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiLDeletar.setMnemonic('d');
        jmiLDeletar.setText("Deletar");
        jmLivro.add(jmiLDeletar);

        jmGerenciamento.add(jmLivro);

        jMenuBar1.add(jmGerenciamento);

        jMenu2.setText("Venda Livro");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCCadastrarActionPerformed
        JOptionPane.showMessageDialog(this, "Cadastrar Cliente!");
    }//GEN-LAST:event_jmiCCadastrarActionPerformed

    private void jmiCEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCEditarActionPerformed
        JOptionPane.showMessageDialog(this, "Editar Cliente!");
    }//GEN-LAST:event_jmiCEditarActionPerformed

    private void jmiLCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLCadastrarActionPerformed
        JOptionPane.showMessageDialog(this, "Cadastrar Livro!");
    }//GEN-LAST:event_jmiLCadastrarActionPerformed

    private void jmiCListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCListarActionPerformed
        JOptionPane.showMessageDialog(this, "Listar Cliente!");
    }//GEN-LAST:event_jmiCListarActionPerformed

    private void jmiCDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCDeletarActionPerformed
        JOptionPane.showMessageDialog(this, "Deletar Cliente!");
    }//GEN-LAST:event_jmiCDeletarActionPerformed

    private void jmiECadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiECadastrarActionPerformed
        JOptionPane.showMessageDialog(this, "Cadastrar Editora!");
    }//GEN-LAST:event_jmiECadastrarActionPerformed

    private void jmiEEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEEditarActionPerformed
        JOptionPane.showMessageDialog(this, "Editar Editora!");
    }//GEN-LAST:event_jmiEEditarActionPerformed

    private void jmiEListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEListarActionPerformed
       JOptionPane.showMessageDialog(this, "Listar Editora!");
    }//GEN-LAST:event_jmiEListarActionPerformed

    private void jmiEDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEDeletarActionPerformed
        JOptionPane.showMessageDialog(this, "Deletar Editora!");
    }//GEN-LAST:event_jmiEDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenu jmEditora;
    private javax.swing.JMenu jmGerenciamento;
    private javax.swing.JMenu jmLivro;
    private javax.swing.JMenuItem jmiCCadastrar;
    private javax.swing.JMenuItem jmiCDeletar;
    private javax.swing.JMenuItem jmiCEditar;
    private javax.swing.JMenuItem jmiCListar;
    private javax.swing.JMenuItem jmiECadastrar;
    private javax.swing.JMenuItem jmiEDeletar;
    private javax.swing.JMenuItem jmiEEditar;
    private javax.swing.JMenuItem jmiEListar;
    private javax.swing.JMenuItem jmiLCadastrar;
    private javax.swing.JMenuItem jmiLDeletar;
    private javax.swing.JMenuItem jmiLEditar;
    private javax.swing.JMenuItem jmiLListar;
    // End of variables declaration//GEN-END:variables
}
